version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - npm install
  build:
    commands:
      - npm run build
artifacts:
  files:
    - '*/'
  discard-paths: 'no'
  base-directory: ./

